# Generated by Django 4.0.2 on 2022-02-28 00:24

from django.conf import settings
from django.db import migrations, models
import lampi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lampi',
            fields=[
                ('name', models.CharField(default='My LAMPI', max_length=50)),
                ('device_id', models.CharField(max_length=12,
                 primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=models.SET(
                    lampi.models.get_parked_user),
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
