# Generated by Django 4.0.2 on 2022-03-14 05:58

from django.db import migrations, models
import lampi.models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0002_alter_lampi_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(default=lampi.models.generate_association_code, max_length=32),
        ),
    ]
