# Generated by Django 4.0.2 on 2022-04-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0003_lampi_association_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampi',
            name='device_id',
            field=models.CharField(db_index=True, max_length=12, primary_key=True, serialize=False),
        ),
    ]
