# Generated by Django 4.0.2 on 2022-04-26 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0004_alter_lampi_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LampiPref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('settings', models.CharField(default="{'color': {'h': 1, 's':1}, 'brightness': 1}", max_length=50)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lampi.lampi')),
            ],
        ),
    ]
