# Generated by Django 4.0.2 on 2022-04-28 02:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0006_alter_lampipref_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lampipref',
            name='user_name',
        ),
        migrations.AddField(
            model_name='lampipref',
            name='username',
            field=models.CharField(db_column='user_name', default='default', max_length=100),
            preserve_default=False,
        ),
    ]
