# Generated by Django 4.0.2 on 2022-04-28 02:48

from django.conf import settings
from django.db import migrations, models
import lampi.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lampi', '0007_remove_lampipref_user_name_lampipref_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('name', models.CharField(default='My Camera', max_length=50)),
                ('device_id', models.CharField(db_index=True, max_length=12, primary_key=True, serialize=False)),
                ('association_code', models.CharField(default=lampi.models.generate_association_code, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=models.SET(lampi.models.get_parked_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
